### ISSUE TITLE
Bundler cant use gems in final jar

### ISSUE THREAD

**Issue by rootcfg** [rammpeter/jarbler#17]
Sorry what im doing wrong?

[dima@redhat /home/dima/dima/jdogs_email/jdogs_test]$ jruby /home/dima/dima/jdogs_email/bin/jarble

Jarbler release 0.3.0, 2024-06-16 ( https://github.com/rammpeter/jarbler )

No configuration file found at /home/dima/dima/jdogs_email/jdogs_test/config/jarble.rb. Using default values.

Used configuration values are:

  excludes:                 ["tmp/cache", "tmp/pids", "tmp/sockets", "vendor/bundle", "vendor/cache", "vendor/ruby"]

  executable:               bin/rails

  executable_params:        ["server", "-e", "production", "-p", "8080"]

  includes:                 ["app", "bin", "config", "config.ru", "db", "Gemfile", "Gemfile.lock", "lib", "log", "public", "Rakefile", "script", "vendor", "tmp"]

  jar_name:                 jdogs_test.jar

  jruby_version:            9.4.3.0

Created jar file /home/dima/dima/jdogs_email/jdogs_test/jdogs_test.jar

[dima@redhat /home/dima/dima/jdogs_email/jdogs_test]$ java -jar jdogs_test.jar

Extracting files from /home/dima/dima/jdogs_email/jdogs_test/jdogs_test.jar to /tmp/703bce8d-ccfe-41dc-9bc4-cd2d0b79a748

2024-07-02T11:46:04.982+03:00 [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem

Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.

**Could not find rails-7.0.8.4, sprockets-rails-3.4.2, activerecord-jdbcsqlite3-adapter-70.2-java, puma-5.6.8-java, importmap-rails-2.0.1, turbo-rails-2.0.5, stimulus-rails-1.3.3, jbuilder-2.12.0, tzinfo-data-1.2024.1, opensearch-ruby-3.3.0, jarbler-0.3.0, chartkick-5.0.7, lazy_high_charts-1.6.1, plotly-0.0.1, c3-rails-0.4.18, gnuplotrb-0.4.0, rgl-0.6.6, daru-0.3, gruff-0.25.0-java, svg-graph-2.2.2, dotenv-3.1.2, actioncable-7.0.8.4, actionmailbox-7.0.8.4, actionmailer-7.0.8.4, actionpack-7.0.8.4, actiontext-7.0.8.4, actionview-7.0.8.4, activejob-7.0.8.4, activemodel-7.0.8.4, activerecord-7.0.8.4, activestorage-7.0.8.4, activesupport-7.0.8.4, railties-7.0.8.4, sprockets-4.2.1, activerecord-jdbc-adapter-70.2-java, jdbc-sqlite3-3.42.0.0, nio4r-2.7.3-java, tzinfo-2.0.6, faraday-2.9.2, multi_json-1.15.0, hash-deep-merge-0.1.1, json-2.7.2-java, hamster-3.0.0, pairing_heap-3.1.0, rexml-3.3.0, stream-0.5.5, packable-1.3.18, bigdecimal-3.1.8-java, histogram-0.2.4.1, rmagick4j-0.3.9-java, websocket-driver-0.7.6-java, mail-2.8.1, net-imap-0.4.13, net-pop-0.1.2, net-smtp-0.5.0, rails-dom-testing-2.2.0, rack-2.2.9, rack-test-2.1.0, rails-html-sanitizer-1.6.0, globalid-1.2.1, nokogiri-1.16.6-java, builder-3.3.0, erubi-1.13.0, marcel-1.0.4, mini_mime-1.1.5, concurrent-ruby-1.3.3, i18n-1.14.5, minitest-5.24.0, method_source-1.1.0, rake-13.2.1, thor-1.3.1, zeitwerk-2.6.16, faraday-net_http-3.1.0, strscan-3.1.0-java, websocket-extensions-0.1.5, date-3.3.4-java, net-protocol-0.2.2, loofah-2.22.0, racc-1.8.0-java, net-http-0.4.1, timeout-0.4.1, crass-1.0.6, uri-0.13.0 in locally installed gems**

Run bundle install --gemfile /tmp/703bce8d-ccfe-41dc-9bc4-cd2d0b79a748/app_root/Gemfile to install missing gems.

**Comment by rammpeter** [comment]
@rootcfg Could you please try if one of the following approaches are fixing the problem:
1. Set the mentioned JDK settings before executing 'java -jar jdogs_test.jar'
```
export JAVA_OPTS="--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED"
```
2. Use the last JRuby version 9.4.8.0 for bundling with Jarbler

**Comment by rammpeter** [comment]
@rootcfg: Additional question: Which Java version do you use?

**Comment by rootcfg** [comment]
Thanks you for reaction, i think that my problem near the env. Because im using jar from Maven and doing something like this - 

2283  [ 2024-07-02 14:40:39 MSK ] export GEM_HOME=/home/dima/dima/jdogs_email/gems/
 2284  [ 2024-07-02 14:40:45 MSK ] export GEM_PATH=/home/dima/dima/jdogs_email/
 2285  [ 2024-07-02 14:40:58 MSK ] alias jruby='java --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED  -jar /home/dima/dima/jdogs_email/jruby-complete-9.4.3.0.jar -S'
